### ISSUE TITLE
Agregar estilo a pantalla de inicio de sesión

### ISSUE THREAD

**Issue by tavo1998** [micardona96/UNIPARCHE#16]
Modificar el diseño de la pantalla de inicio de sesión para que sea más llamativa y esté relacionado con el propósito de la aplicación.

![WhatsApp Image 2020-04-24 at 11 05 35 AM](https://user-images.githubusercontent.com/44323842/80233312-e5735000-861b-11ea-82ea-1dc34257b43c.jpeg)

**Comment by micardona96** [comment]
![localhost_8080_(iPhone 5_SE)](https://user-images.githubusercontent.com/37484798/81809730-7042be80-94e7-11ea-8995-c16e4d4d36b7.png)
