### ISSUE TITLE
Eliminación de chat mediante función programada

### ISSUE THREAD

**Issue by tavo1998** [micardona96/UNIPARCHE#17]
Cuando el tiempo de vida de los chat activos lleguen a su fin no se debe realizar la eliminación inmediata, se debe programar una función en firebase que se ejecute cada día a una determinada hora y realice la eliminación de todos los chats que han finalizado.

**Comment by micardona96** [comment]
Se ajusta para que los datos y el chat no se accesible desde la interfaz grafica.

**Comment by micardona96** [comment]
completado
